### PR TITLE
Avatus and more

### PR DESCRIPTION
**Pull request by Immemor**
Many changes.

### CODE REVIEW

**Comment by ghost** [comment]
Nice commits Immenor.

Now WatchUnit check everything right ? Buff - Debuf - Cast ?

**Comment by Immemor** [comment]
yes

**Comment by Immemor** [comment]
debuff for players and buff for foes are always enabled.

I removed any filter, because there isn't a lot of spell to detect, so I choose the easy implementation.

I try also , the new event from carbine. And as I thought, that create too much interruptions.

**Comment by Immemor** [comment]
Kinae do you review it, or for this time you will trust me ?

By review, I expect: The style, and after algorithm question or bug detection.

**Comment by ghost** [comment]
I trust you, I did a fast check to see what stuff has changed :-)

**Pull request merged**
