### PR TITLE
Boss

### PR DESCRIPTION
**Pull request by Immemor**
Mainly few French translations.

### CODE REVIEW

**Comment by Immemor** [comment]
Ok, I repushed a version on current master branch.

The unique diff is: PlaceSpawnPos and SPREAD_POS removed.

**Comment by NielsH** [comment]
Cool, is INFORMATIC_CLOUD in EpLogicEarth in preparation of another change? Since it doesn't seem to be used now. Besides that I'm fine with it :+1:

**Comment by Immemor** [comment]
Yes and no, I hesitate to keep it.
I'm share between create the define if we need it later to avoid to search it, and the idea to avoid some dead code.

**Comment by NielsH** [comment]
Well personally I'm fine with having it, I don't think it hurts. Though of course with the awesome logging feature it won't be hard to search for it at that point ;)

**Pull request merged**
