### PR TITLE
Bugfix: some TimerBar labels translations are missing, refs #150

### PR DESCRIPTION
**Pull request by olbat**
Automagically fixed by:

``` bash
find Encounters/ -type f -name '*.lua' | xargs -n1 sed -i 's/\(AddTimerBar(\ *"[^"]\+"\ *,\ *\)\("[^"]\+"\)/\1self.L[\2]/g'
```

### CODE REVIEW

**Comment by Immemor** [comment]
It's wrong.

You haven't read AddTimerBar function. This last support a text as the key to found the text.

**Comment by olbat** [comment]
Okay so there is some text entries that should not be translated (see #150):

``` bash
$ grep -r 'AddTimerBar' | grep 'self\.L' | head -4
Encounters/DS/SystemDaemons.lua:    mod:AddTimerBar("SDWAVE", self.L["[%u] WAVE"]:format(1), 15, mod:GetSetting("SoundWave"))
Encounters/DS/SystemDaemons.lua:                mod:AddTimerBar("SDWAVE", self.L["[%u] WAVE"]:format(sdwaveCount + 1), 50, mod:GetSetting("SoundWave"))
Encounters/DS/SystemDaemons.lua:                mod:AddTimerBar("SDWAVE", self.L["[%u] MINIBOSS"]:format(sdwaveCount + 1), 50, mod:GetSetting("SoundWave"))
Encounters/DS/SystemDaemons.lua:                mod:AddTimerBar("SDWAVE", self.L["[%u] WAVE"]:format(sdwaveCount + 1), 50, mod:GetSetting("SoundWave"))

$ grep -r 'AddTimerBar' | grep -c 'self\.L'
201
```

Do you want me to fix them ?

**Comment by olbat** [comment]
Btw, I can't find anything in the `AddTimerBar` (aka. `TimerManager:AddBar`) that translates the text entries ...

**Comment by olbat** [comment]
Same issue with 3-4 `AddMsg` calls (some are called with the translated text, some arent) ...

**Comment by olbat** [comment]
> You haven't read AddTimerBar function. This last support a text as the key to found the text.

Erm if it does, there must be a bug somewhere because the strings that contains a `%s` or `%u` replacement expressions are rewritten before calling this function (so it will not match any traductions) ...

**Comment by Immemor** [comment]
Hum.

For the moment, I did that only for timers. The goal is to reduce the code complexity in encounters database.

in `Encounters/BossPrototype.lua`, You have:

``` lua
function EncounterPrototype:AddTimerBar(sKey, sEnglishText, nDuration, bEmphasize, fHandler, tClass, tData)
    local tOptions = nil
    local sLocalText = self.L[sEnglishText]
```

if the sEnglishText key is not found in L, the sEnglishText value will be used.
The L variable is a reference to GeminiLocal library.

Which means, for simple message in encounter, the key can be directly used, and so that replace all  `self.L[" XXX "]` by  `" XXX "`

but for dynamic text, the old method still working:

``` lua
mod:AddTimerBar(  ... self.L[" XXX "]:format(myVariables), ... )
```

In your grep, I see only AddTimerBar reference.

**Comment by olbat** [comment]
> For the moment, I did that only for timers. The goal is to reduce the code complexity in encounters database.

Erm okay, so do you want me to strip the useless `self.L[...]` codes from `AddTimerBar` calls to harmonize everything ?

> In your grep, I see only AddTimerBar reference.

Oops, I was speaking about `AddMsg`:

``` bash
$ grep -r 'AddMsg' Encounters/ | grep -v 'self\.L'
Encounters/DS/EpAirEarth.lua:        core:AddMsg("QUAKE", "JUMP !", 3, mod:GetSetting("SoundQuakeJump") and "Beware")
Encounters/DS/EpFireLife.lua:            core:AddMsg("NOHEAL", "No-Healing Debuff!", 5, mod:GetSetting("SoundNoHealDebuff") and "Alarm")
Encounters/DS/EpFireWater.lua:                core:AddMsg("STACK", sMessage, 5, mod:GetSetting("SoundHighDebuffStacks") and "Beware")
Encounters/DS/EpLogicEarth.lua:        core:AddMsg("SNAKE", sSnakeOnX, 5, sSound, "Blue")
Encounters/DS/Maelstrom.lua:            core:AddMsg(sKey, sMessage, 5, sSoundFile, "Blue")
Encounters/DS/miniboss/Logic_Abstract_Augmentation_Algorithm.lua:    core:AddMsg("KICKER", sMessage, INTERRUPT_INTERVAL, nil, "red")
Encounters/DS/VolatilyLattice.lua:            core:AddMsg("BEAM", sText, 5, mod:GetSetting("SoundBeamOnYou") and "RunAway")
Encounters/DS/VolatilyLattice.lua:            core:AddMsg("BEAM", sText, 5, mod:GetSetting("SoundBeamOnOther") and "Info", "Blue")
```

(only few of them are not translated, the others are matching because they are using variables)

**Comment by Immemor** [comment]
About the AddMsg, it's should be better to add the same mechanism as the AddTimerBar.

I prefer to reduce the repetition instead of continue to write it.

**Comment by olbat** [comment]
You're right, it's probably better this way

**Comment by olbat** [comment]
Just in cast, the automagic command:

``` bash
find Encounters/ -type f -name '*.lua' | xargs -n1 sed -i 's/\(AddMsg(\ *"[^"]\+"\ *,\ *\)self.L\[\("[^"]\+"\)\]\(\ *,\)/\1\2\3/g'
```

**Pull request closed without merging**
