### PR TITLE
Add settings & make sure UnitEnteredCombat is working again

### PR DESCRIPTION
**Pull request by NielsH**
I'd like to add this into the master. It adds the settings for the bosses that we hadn't added before.
It also adds a change that should fix issues with UnitEnteredCombat, preventing the boss mods from loading. I think we should add this even if the plan is to change it again later - so we at least have something working for now!

Also adds a warning for Stitching Strain on the Convergence fight, something people asked for on Curse.

### CODE REVIEW

**Comment by Immemor** [comment]
Well, I think you can factorize your code.

GetSoundSetting and GetSetting, shouldn't be copied in every boss files.

There is a class for that in BossPrototype. That should give something

``` lua
function boss:GetSoundSetting(sound, key)
  return core.settings[self:GetName()][key]
end
```

**Comment by NielsH** [comment]
Well I guess that's possible, but we will need a boss:RegisterSettings then I think. Because the settings are core.settings["DS"]["Lattice"] for example. Doing core.settings[self:GetName()] would make it core.settings["Lattice"].

**Comment by Immemor** [comment]
If you want organize your database, you should use prefix and suffix only.
Create an array of array, bring more complexity than a real advantage.

By example you can prefix your options like:

``` lua
core.settings["DS_Lattice_myoption1"]
```

or, the second code style. As u wish. 

``` lua
core.settings.DS_Lattice_myoption1
```

**Comment by NielsH** [comment]
I quite liked the table/array setup for separation of stuff, but it's true it's a bit of a pain for management sometimes...

I've changed stuff around a bit so mod:GetSetting() can be used

**Comment by Immemor** [comment]
Same story for dist2unit

That shouldn't be duplicated. you have a boss class for that.

Maybe you should split your branch, because you have mixed:
-  bug fix, 
- settings 
- and convergence improvements.

Generaly we try to push only 1 idea. 1 feature. It's easier to review to avoid regression.

**Comment by NielsH** [comment]
The dist2unit thing has already been used in multiple places. Yes it'd be good to change, but I don't think it should be changed now/in this commit. Rather have that as a separate improvement to replace -all- of the dist2unit calls to a common handler.

**Comment by Immemor** [comment]
Well, if I was you.
I would like to prepare 1 branch with 1 commit about the dist2unit. It's quick to do, and quick to review.

After that, this branch will not increase this mistake. 
I process like that because a small error or small bug will become big few weeks later. And a big bug is hard to kill. ^^
I say that by experience, only.

**Comment by Immemor** [comment]
I feel you aren't really happy to rework your branch.
So I help you as I can. I did the cleaning about dist2unit function.
See: https://github.com/NielsH/RaidCore/pull/40

**Comment by NielsH** [comment]
Well, it's not that I don't agree with you that it can be changed and that a common handler is better, I just kinda want things to... progress. Rewriting existing things that do work already, even if it doesn't take a lot of time will delay a next release. I really want to be able to push a new version to Curse, so people can use all the cool new features! :+1: 

Anyways, I wanted to pick it up today - but thank you for doing it. I'll open a separate issue to see how/when we can go about releasing stuff to Curse!

**Comment by NielsH** [comment]
Made a new request to merge it :) See https://github.com/NielsH/RaidCore/pull/45

**Pull request closed without merging**
