### PR TITLE
Added global alert sound toggle

### PR DESCRIPTION
**Pull request by Gil-B**

### CODE REVIEW

**Comment by NielsH** [comment]
Hey,

General message up front: Could you add the KamiNuvini account in-game? Chatting might make some things easier. I saw you're also on the EU PvE realm, correct?

We don't use GeminiDB for settings, but our own implementation which you can see below - it is saved on Character Level:
https://github.com/NielsH/RaidCore/blob/master/RaidCore.lua#L38
https://github.com/NielsH/RaidCore/blob/master/RaidCore.lua#L250

I'm not sure if you're referring to the _G space, which is used in multiple locations, or the naming @Wobel used for his variables (local GlobalSettings). Regarding the first, a lot of this was made a while back, and I'm sure there are a lot of improvements/better practices possible. It's really great you seem to know a good amount of them, since a lot of this came about through trial and error. Making things that work, work better with best practices is great.

For the latter, I spoke with Wobel, we'll read the sound directly from the raidcore settings (self.settings), which is a better way imo.

**Comment by Immemor** [comment]
Yep, it's exact. I added you. You are on dominion side

Some of my friend told me, there is a guy called Kami. I didn't known which account it was on github. Now I known ^^.

Is it possible to communicate all together in a Circle ? I never try between dominion and Exile.

For the code, I will look what you linked first. Maybe you found a better way than geminiDb. ^^

**Comment by Gil-B** [comment]
Sorted the changes we spoke of and the accidental newline.

I think we should use Immemor's generic way, but we should just change all the current code that uses our old method in one commit later I guess.

**Comment by NielsH** [comment]
Since it couldn't be merged automagically, I've added in your changes in a separate commit over here: https://github.com/NielsH/RaidCore/commit/d899de0c9a65d6ba7df4d3c6f5d39b2ec78441a4
Cheers :)

For the settings ideally we want a common handler as you suggest, but because of our settings table layout this is a bit tricky because the depth of our tables differs a bit. We would need a function that strips away identifier[1] because it is the button, and then dynamically saves the setting to self.settings[identifier{2345}] depending on the amount of keys identifier gets via SplitString. I've had a go it this but couldn't get it to work after some trying.

Did you have another idea for how to structure settings? I do think it would be cool to be able to have multiple levels of depth in the settings, as long as the window names are simply separated with the _ (undescore) character. In the end we will have -a lot- of settings; all bosses of DS, GA, new upcoming raids, if we're being ambitious also dungeons, so it'd be great if we can have a good way of structuring all that. I do like the current way of how it is displayed in DefaultSettings in RaidCore.lua

**Comment by Immemor** [comment]
well, I tried the most simplest structure as I can, to reduced the amount of code to do.

So as you said, the KeyName must be carefully chosen.
I start with this option on my side:

``` lua
  profile = {
    dbm = {
      version = DRUSERABOSSMODS_VERSION,
    },
    custom = {
      bar_threshold_n2h = 0,
      bar_inversesort_normal = false,
      bar_inversesort_highlight = false,
      bar_add2top_normal = false,
      bar_add2top_highlight = false,
      bar_fill_normal = false,
      bar_fill_highlight = false,
      bar_displaytime_normal = true,
      bar_displaytime_highlight = true,
      bar_texture_normal = "restrat1",
      bar_texture_highlight = "restrat1",
      bar_height_normal = 25,
      bar_height_highlight = 30,
      bar_font_normal = "CRB_Interface11_BO",
      bar_font_highlight = "CRB_Interface12_BO"
```

**Comment by Gil-B** [comment]
Cool thanks.
I'll close this then :)

**Comment by Gil-B** [comment]
@Immemor I don't think circles work cross faction unfortunately :(

**Pull request closed without merging**
