### PR TITLE
All

### PR DESCRIPTION
**Pull request by Immemor**
I put all my changes in this branch.

For test usage in raid between us.

### CODE REVIEW

**Comment by Immemor** [comment]
- 1 timer is 0.010ms / frame
- 2 timers is between 0.011ms/f and 0.02ms
- 4 timers is between 0.017ms/f and 0.027ms
- 8 timers is between 0.032ms/f and 0.040ms

Measures done with `/raidc bar something 300`
- 1 Unit watched: between 0.020 ms and 0.040 ms
- 2 Unit watched: between 0.050 ms and 0.060 ms
- 4 Unit watched: between 0.080 ms and 0.095 ms

Measures done with `/raidc unit`

**Comment by Immemor** [comment]
I started to add a default color for timers bar, I haven't finished. But if someone want to see...

I will terminated for monday or before. And I think to prepare a v3.0-beta version.

**Comment by Immemor** [comment]
Well, as NielsH stop to play to Wildstar, I will prepare an v3.0 - alpha version.

**Comment by adamjedlicka** [comment]
Damn that sucks. I know this isn't about this issue, but if you will need help with anything let me know.

**Comment by Immemor** [comment]
Well, I have many month of dev in mind. I will continue at the same rate.

At least, I will try. Because I have my third interview for a job. And If I'm taken, that means I will code in the subway after ^^.

**Pull request merged**
