### PR TITLE
Encounters/Y83 - Improvements and fixes

### PR DESCRIPTION
**Pull request by adamjedlicka**
- Fixed line to irradiate
- Added marks '!' on people with 'Strain Incubation' debuff
- Added three lines to incinerator (front red and two green (120 a 240
  degrees from it)
- Removed timer bars of Strain Incubation debuff - pointless and take
  space

### CODE REVIEW

**Comment by ghost** [comment]
I am working on it (Kinae from Eugenified). I will share it as soon as possible. Tonight I will do the last tests

**Comment by adamjedlicka** [comment]
Ok. I saw it on Nippe's stream and heard you are doing on it but haven't found it anywhere, so I did my own version for us.

**Comment by ghost** [comment]
Yeah fair enough. Anyway, mine is very developped (+500lines maybe) but I didn't get time to test it a lot (maybe I couldcome to your raid tonight to raid (and test it) with you utopia ? yes yes ? :-) ) I want to do augmentor HM =(

**Comment by adamjedlicka** [comment]
Nice. Unfortunately we don't raid on Mondays and yesterday we killed it on normal (for parses :D ) so no testing :(

**Comment by ghost** [comment]
Gonna test tonight if poeple shows up to clear trash, I just need to pull the boss alone. I will let you know here guyz.

**Comment by Immemor** [comment]
^^, nice.

Be careful Kina, Draw something take a lot of CPU today. Keep in mind to not flood the user interface too.

Otherwise, space or tabulation... I think whole developers are shared about this question.
My arguments are:
- No tools to set with space.
- You can align to the bracket to avoid line too long.
- PEP8 recommend spaces over tabulation too.

**Comment by adamjedlicka** [comment]
I will try to remember to use spaces in RaidCore but it's weird.

**Comment by Immemor** [comment]
weird: It's your point of view.

LUA traditional coding standard is the PEP8 which is used in python. And this coding standard recommend space.

If you want learn why, all is explained in the PEP8 website.

**Comment by Immemor** [comment]
Kina, did you have a WIP branch to proposal to us ? or do you need few days  ?
I would like to review it before push. And after the review, a final test could be needed.

Also, did you try to manage idea bring by Adam in your branch ?

**Comment by Immemor** [comment]
Another details, could add the ', closes #91.' in your commit message.

**Pull request closed without merging**
