### PR TITLE
Improve World Marker handling

### PR DESCRIPTION
**Pull request by NielsH**
There are some improvements possible for the way World Markers are currently handled. This should fix some of the restrictions and issues that are currently happening for some bosses. See individual commit messages for details.

### CODE REVIEW

**Comment by NielsH** [comment]
Sure, we can also update the position. For removing them, 1 or 2 functions... I don't really mind a separate remove mark function, it would be more consistent with the other functions that also have a separate Add and Remove function.  

Or do you think it'd be much better just having it in one? (I'm fine either way :))

**Comment by NielsH** [comment]
Alright, changed some stuff in the latest commit. We still have 2 functions for add/remove marks, but if you think it's better to have it in one it's easy to change, so let me know :+1:

**Comment by Immemor** [comment]
Well, that depend.

Which one:
- take less code to write ?
- easier to valid ?
- easier to maintain ?
- is the most simple, and so the most flexible ?

Note:

If "Mark" is the key in the array markFrame. That should be the first argument.

``` lua
function RaidCore:SetWorldMarker(position, mark)
```

like that, I thinking to:

``` lua
-- Set a text at a fixed position in the world.
-- @param key  That could be anything. There is 1 mark for 1 key.
-- @param tPosition  It's the position in the 3D world. nil value is allowed.
-- @param sText  Text to display on the marker
--
-- Set a nil position to delete a maker.
-- Ex:   SetWorldMarker("X")
local _tWorldMarkers = {}
function RaidCore:SetWorldMarker(key, tPosition, sText)
  assert(key)
  local tWorldMarker = _tWorldMarkers[key]
  if  tWorldMarker == nil and tPosition then
    -- Create this marker
  elseif  tWorldMarker and tPosition then
    -- Update this marker
  elseif tWorldMarker and tPosition == nil then
    -- Delete this marker.
  end
end
```

Hum,  we win 2 common lines on 3 different behaviors. It's not really huge.
After, you can create 3 functions: Create, Update, Delete

But 2 functions, where 1 will manager different feature seem not to be the good idea.

**Comment by Immemor** [comment]
With my proposal, you can only update the position, if you want. just few if to add.

**Comment by NielsH** [comment]
Creating 3 functions (create/update/delete) sounds good to me - though of course it will be "more lines of code" in that sense. However personally I don't think focusing on minimizing the amount of code really matters in cases like this. It'll be a few lines more or less, not really significant anyways :)

So end result will be we could call the "wrapper" function which will determine if we're creating, updating, or deleting and call the correct function for that. And we'd still be able to directly call those functions directly if we want to :+1: 

Also 1 question, what does `assert(key)` do? Is it similar to `if not key then return end` ?

**Comment by Immemor** [comment]
assert will raise an error if the condition is false or nil.
It's a classic when we code something.

**Comment by Immemor** [comment]
About the wrapper is a good idea too.

Like that your "create, update and delete" functions can be private to the file with "local function" keyword.

**Comment by Immemor** [comment]
An another things, Do you want to push that for this April delivery ?

For me April delievery was almost close. Only bug fix can be pushed in master branch.

**Comment by NielsH** [comment]
Awesome - and yeah, I'd like to include it in the April release. Especially
marks not resetting properly is something I often hear from people in the
raid.

For this reset I want to make sure that bosses activate properly again and
start when the fight engages. This was a problem last week (probably
because of the settings derp) so I want to be sure that works at least.
Otherwise it'd be a regression, and bosses not even activating would be
quite bad in a new release... heh ^^

After that all is good for me to release! :-)

**Comment by Immemor** [comment]
Ok.

I have asked, because we don't created any ticket to manage this in april milestone.
So to organize us works together, that should be better to create ticket instead all the code. Just to avoid two person which work on the same topic.

Well, for the next time. Maybe should we delay the May delivery for beginning of June, in milestone declaration of this project.

**Comment by NielsH** [comment]
Okay so I changed some things so we use a wrapper functions now. I initially did it with the local functions - but this cannot work, since we cannot access `self` inside local functions (for self.worldmarker and the LoadForm calls).

**Comment by Immemor** [comment]
I will look that after my raid.

**Comment by NielsH** [comment]
@Immemor Did you want anything changed in this commit or is it ok to merge in?

**Comment by Immemor** [comment]
well, as you create, delete the same code, maybe you should squash all of them in 1 commit.

**Comment by NielsH** [comment]
Yeah, if the end result of https://github.com/NielsH/RaidCore/commits/ae993d53cb240fd7172092e989b59617f4a9e0dd is okay with you I'll add that I'll combine it all into one commit and make a pull request for that :)

**Comment by Immemor** [comment]
And,

CreateWorldMarker Update, Delete should be local, I think so

**Comment by NielsH** [comment]
I initially did that as well - but I cannot access the self variable inside a local function. That's why i changed it to be a "normal"function. Unless you think it's a good idea to pass that as an argument?

**Comment by Immemor** [comment]
Yes, I did it in CombatInterface.lua file.

"self"' is added when you call a function in a table, before and after the call.

But when you play with function outside the table, you must add it. Like in CombatInterface.lua:

``` lua
local function ManagerCall(sMethod, ...)
    ...
    -- Protected call.
    if fMethod then
        local s, sErrMsg = pcall(fMethod, _tCombatManager, ...)
        if not s then
            --@alpha@
            Print(sMethod .. ": " .. sErrMsg)
            --@end-alpha@
    ....
```

_tCombatManager is in fact equal to RaidCore. And that will become "self" in the function called.

**Comment by Immemor** [comment]
Ok, I rebased your work on master and squash commit between them.

So I'm able to understand a little bit more what you did.

**Comment by NielsH** [comment]
Alright, new commit should fix some stuff. In the xml the visbility is off, and it'll now enable it only if the position is on screen.

For local functions, I'm still not sure how you envision it exactly, sorry. Do you want a new function added in raidcore.lua similar to how you handle ManagerCall in the combatinterface, so I can call through that as a local function?

**Comment by Immemor** [comment]
You managed it very simply. I thought to something more complicated.
Show on/off, I'm agree with the idea.

But:
- You didn't change the previous commit ? with "rebase -i" or "git commit --amend"
- Didn't you forgot to add the xml file in the commit ?

**Comment by NielsH** [comment]
I'm waiting for you to make sure everything is agreed, then I can make a pull request based on master with everything in one commit... the rebase / amend stuff does take me a long time and hassle since I'm not very good at it, so waiting until all changes are agree before doing that :P 

I don't think I forgot to add the xml? Nothing changed there - the default was already non-visible (previously it had the markFrame:Show(true) call)

**Comment by Immemor** [comment]
Sorry, for the delay. I took some days off.

I did the rebase on top of master for you, as there is few conflicts to manage.
After for me, it's deliverable in master.

Remaining points which are:
- To have few functions in local, it's idea of how the code should be organized. I have in mind to provide an access to other class only if needed. But it's not an obligation.
- Should you or not reorganize the commit message. Well, as you wish in fact. I known what contains this commit.

**Comment by NielsH** [comment]
I changed the commit message just now, but I think for now we should leave out the local functions. I'm still not sure how it should be implemented, and I'd love to have this in before drop 5.

**Comment by Immemor** [comment]
Ok, so that means you want do a tag on the current state of master ?

**Comment by Immemor** [comment]
Your turn now, push it. :)

**Comment by NielsH** [comment]
hype

**Pull request merged**
