### PR TITLE
Add new features for CoreY83 based on guild : Eugenified - WL - Utopia

### PR DESCRIPTION
**Pull request by ghost**
Add new features for CoreY83 based on guild : Eugenified - World Last and Utopia.
- Line for the next corrupted boss (10 sec timer)
- Line for the laser (hardmode). Line is red (kill you) and becomes green (safe) when interrupted (players can still view it to anticipate it when the laser respawn)
- 2 Schemas of lines for the digitize telegraph : DPS and Tank
- Unit marked with a "U" when they got the debuff STRAIN_CORRUPTION
- Sound Warning for PUSH at 60% and 20%
- ...

Possibilites to draw line between two world positions.

### CODE REVIEW

**Comment by ghost** [comment]
Final test was done yesterday. Sorry for the late push but I needed to be sure that worked as intented. Open for any reviewer (syntax etc etc)

**Comment by Immemor** [comment]
I will look that.

**Comment by Immemor** [comment]
Do you want any help ?

**Comment by Immemor** [comment]
did u stop the game ?

**Pull request closed without merging**
