### PR TITLE
Add French translations for GA/Kuralak (#140)

### PR DESCRIPTION
**Pull request by olbat**

### CODE REVIEW

**Comment by olbat** [comment]
Logs used to translate: https://gist.github.com/olbat/5c31432b381fa63df915.

**Comment by Immemor** [comment]
During the day, I will take your commits, add the comma forgotten on end of line, and push it for release candidate, because there is no risk.

**Comment by olbat** [comment]
I've made the change (commas)

**Comment by Immemor** [comment]
I did it this morning, and I pushed into master (3.10).

**Pull request closed without merging**
