### PR TITLE
Add French and German automatic translations for each module (#15)

### PR DESCRIPTION
**Pull request by olbat**
Automatic translations were generated using the raidcore-translator script
(http://github.com/olbat/ws-raidcore-translator).

### CODE REVIEW

**Comment by olbat** [comment]
Ok for Gloomclaw, it seems that I've made my run with outdated dumps (did not have access to internet) instead of generating fresh ones.

**Edit**: in fact there is a little bug in the script, it's trying to translate "Gloomclaw is reduced to a weakened state!" (the value) instead of "Gloomclaw is reduced to a weakened state" (the key) so there is no matches in dumps and the translation is not working ... I'm working on a fix ...

**Comment by olbat** [comment]
I've made a fix, the script is now looking for both hash key and hash value before stating that a there is not translation.

What do you prefer: another pull request or a fixup commit ?

**Comment by Immemor** [comment]
as u wish in fact. I have a little preference for a new branch to check the final diff easily.

**Comment by olbat** [comment]
Here is the new pull request #38. I close this one.

**Pull request closed without merging**
