### PR TITLE
RMT changes from our Raidcore

### PR DESCRIPTION
**Pull request by Zeffuro**
Add mechanics for all RMT fights.
Also tons of performance tweaks.

### CODE REVIEW

**Comment by NielsH** [comment]
Hey there,

I don't actively play the game anymore and I believe @Immemor doesn't either so it's tricky for me to test all of your commits.

Do you have a lot of users (perhaps your guild during progression?) that tested these changes? If so I'm OK with merging it as-as.

Having said that if @Immemor is still following and has other thoughts that's fine with me too - I did hand over the project to him and he made a huge amount of changes / improvements to get it to where it is now 👍

**Comment by Zeffuro** [comment]
Yeah we've tested these. We got more but we're still resting other minis. Since ppl quit the game sharing raidcore has been like manually through zips etc. Would be nice if we can somehow get an updated release on Curse.

**Comment by NielsH** [comment]
I have merged your contributions and added it on Curse. It'll take a little while to show up there but usually it's a few hours at most.

Thank you for the contributions, keep up the good work 👍

**Comment by Zod-** [comment]
There are 1 or 2 bugs and a few silent errors due to changes in the draw manager but all in all it's quite stable. We'll get them fixed eventually.

**Comment by Zeffuro** [comment]
Is there a way that we can get access to get our releases out more?
Also could add that this supports RMT in the Addon description on Curse etc.

**Comment by NielsH** [comment]
I am able to add you on Curse so you can upload new releases there - but not on Github - I transferred the repo to @Immemor a while back and only he can change the Github permissions. Now I believe he is still somewhat active as I saw a few comments on Curse from him but the activity was not very often.

I'd still like to get his response on this and see what he thinks / if he can can give push permissions.

**Comment by NielsH** [comment]
Please wait until this weekend to see if @Immemor is still active, otherwise I'll fork the repo and edit the curse settings to point it to the new fork for now so it can be kept updated.

**Comment by NielsH** [comment]
@Zod- and @Jeffroiscool I have forked the repo to https://github.com/NielsH/RaidCore and given you both access to that repository. I have changed the curse project settings to point to that repo as well. I've added @Jeffroiscool to the curse project as a maintainer but I could not find the @Zod- username - if you let me know i'll add you as well.

I believe that's all that's needed for keeping it updated - thanks 👍 
Let me know if I missed/forgot something you also need.

**Comment by Zod-** [comment]
This is me on Curse: https://mods.curse.com/members/ZodBain

**Comment by NielsH** [comment]
@Zod- Added!

**Comment by Zod-** [comment]
@NielsH Thanks for giving us access. I think the curse project is still pointing to Immemors repository though. Atleast clicking on "Source" on the project page leads to here.

**Comment by NielsH** [comment]
@Zod- Thanks, changed it. Thought I had changed all references but missed that one. Should be good now!

**Pull request merged**
