### PR TITLE
Add options for GA bosses

### PR DESCRIPTION
**Pull request by olbat**
I would like to add options support for GA bosses ...
I've tried to look how it's done for DS bosses and did the same but it's not working (I have an error when clicking on the GA tab).
If you have the time to check what's wrong, I'll add the other bosses :)
Thank you in advance !

### CODE REVIEW

**Comment by olbat** [comment]
I have overridden my last modifications, please do not take this PR in account before I repush them.

**Comment by olbat** [comment]
Problem fixed ! :)

**Comment by olbat** [comment]
(I'm in holidays next week so if you answer, I'll make the modifications when I'll be back)

**Comment by Immemor** [comment]
You didn't do a lot of mistake. Very few in fact.

**In first commit, 2 errors** were in 

``` lua
local function OnMenuLeft_CheckUncheck(wndButton, bIsChecked)
```
- Instead of an 'OR' logic , it's an 'AND' logic, in the if with DS and GA.
- The last elsif is an equal check, you written the opposite.

The correct function is:

``` lua
local function OnMenuLeft_CheckUncheck(wndButton, bIsChecked)
    local sButtonName = wndButton:GetName()
    if not bIsChecked then
        local wnd = RaidCore.wndTargetFrame:GetData()
        if wnd then
            wnd:Show(false)
            RaidCore.wndTargetFrame:SetData(nil)
        end
    else
        if sButtonName ~= "Datascape" and sButtonName ~= "Genetic_Archives" then
            local wnd = RaidCore.wndSettings[sButtonName]
            wnd:Show(true)
            RaidCore.wndTargetFrame:SetData(wnd)
        end
    end

    if sButtonName == "Datascape" then
        RaidCore.wndModuleList["DS"]:Show(bIsChecked)
    elseif sButtonName == "Genetic_Archives" then
        RaidCore.wndModuleList["GA"]:Show(bIsChecked)
    end
end
```

**After, in the commit message, I don't add the file as prefix, only the folder.**

Instead of _"Encounters/GA/ExperimentX89: Add options"_, it's more _"Encounters/GA: Add Experiment X89"_
The idea is more to indicate a module in the prefix. Only that.

**In the PhageMaw commit, button name is not "Encounters_Phagemaw_OtherBombsMarkers" but "Encounters_PhageMaw_OtherBombsMarkers"**, options are found with name registered in the encounter file, not with the array called "wndSetting". Later I will erased this table, to reach something more automatic.

Here you branch reviewed and fixed by me:
https://github.com/NielsH/RaidCore/tree/ga_olbat

**I did some changes in all this commits**:
- Kuralak: I changed the description "Play warning sound for X", by "Play count down sound for X"
- Prototype and Phage Council, I added a information window to indicate that there is no settings for the moment.

**Another topic:** What your name in game ? I could add you as contributer in "about us" windows.

**Comment by Immemor** [comment]
tell me if you are agree with you branch fixed.

**Comment by Immemor** [comment]
Hum, i fixed all mistakes, but there is some strange piece of code:
- The option LineSmallOhmnas on Ohmna is not for mini Ohmna in P2, but it's for Ohmna itself. So the description don't match.
- Be careful, you have added some tabulation instead of space in the ohmna code.

I push again the branch.

**Comment by olbat** [comment]
Hi there,
First of all, thank you for your time :)
For the two mistakes, I didn't understand all the code, thanks for your advices :)

I'm ok with your changes and for Ohmna, you're right, it should be changed (for the tabs, I'll not forget to rewrite them to spaces next time I propose a PR).

My character's name is Olbat Crotinus, feel free to add me to the about section if you think it's justified :)

**Comment by olbat** [comment]
And thank you for your explanations, I have a better understanding of the code now :)
It will probably help for future modifications :)

**Comment by olbat** [comment]
Btw, i only made some translations and that options thing is pretty much nothing so I don't really think that my name should be placed next to the author's ones that made all the work :)

**Comment by olbat** [comment]
I just saw that you added my character's name to the author's list, thank you ! :)

Do you think that it will be possible to add my guild's name: Paradoxe / http://paradoxe.ws/ (as for the other authors/contributors) ?

**Comment by Immemor** [comment]
sure

**Pull request closed without merging**
