### PR TITLE
Full rework of bar service, closes #52 and #89

### LINKED ISSUE #52: Health tracked on unit
I'm terribly disturb with RaidCore, about the current implementation of health bar on screen.

On DruseraBossMods, I added the a cast bar. And so, it's like to have a automatic focus.

So, for me RaidCore should:
- Add the cast bar.
- Add the absorb bar if exist
- Add the shield bar if exist

And for the the design of ForgeUI, could be great.

### PR DESCRIPTION
**Pull request by Immemor**
- New Bar design
- CPU improvements
- Memory reductions

First implementation, which I will test this night (Tuesday 18).
There are more or same features as current Bar system.

### CODE REVIEW

**Comment by Immemor** [comment]
hum, the unit mark is not totally operationnal on the left side of unit frame.

Otherwise, no big problem.

**Comment by NielsH** [comment]
Hey, sounds good.. Sorry for late responses , I'll try to look at it
tomorrow and get back to you :)

**Comment by Immemor** [comment]
Ok, I repushed this branch with the fix about mark.
I don't see anything else, for the moment.

**Comment by Immemor** [comment]
A small preview with test mob.

http://hpics.li/112ad24

**Comment by Immemor** [comment]
hum, I will decrease a little bit the update frequency.

**Pull request closed without merging**
