### PR TITLE
Added color paramter for Bar functions

### PR DESCRIPTION
**Pull request by adamjedlicka**
- this change allows custom bar colors for better clarity
- doesn't break anything, only adds more functionality

there's screenshot how it looks like: http://i.imgur.com/BLxZ6ou.jpg and how calls looks like

EDIT: The bars look like different because I'm using my ForgeUI style for it. It doesn't alter logic of it in any way so this works even without it.

### CODE REVIEW

**Comment by Immemor** [comment]
Hi, It's very nice to help us, but unfortunately I started the task to rework Display files.
And your proposal will create a conflict.

My work will:
- Fix really the #89, because there only a workaround in master.
- Improve cpu load.
- Start to develop other issues which are #72, #52.

And I will add color bar. I saw the result on your video on twitch.

In fact, you have in mind to standardize RaidCore and ForgeUI style ?

**Comment by adamjedlicka** [comment]
Cool that's even better.
About the style: I never wanted to remake main RaidCore's window to ForgeUI style, because you open it once and that's it so only bars, but if you would like to have more parts of RaidCore in ForgeUI style I would be only happy :)

**Comment by Immemor** [comment]
In real life, I lost my job since 1 month now (company closed), but I will probably rework in few weeks.
So, I will first finish the big task, and maybe I will help you after.

About this request itself. Give me 3/4 days before provide you a status on my work. I would like to push only 'ended' work in master, and avoid conflict as possible.

**Comment by Immemor** [comment]
Ok, I will start the integration when I will be back at my home. I will probably show you the draft on this week.

**Pull request closed without merging**
