### PR TITLE
Logger

### PR DESCRIPTION
**Pull request by Immemor**
The review will be a little bit difficult.

I finished a first version of log manager, see /rclog. (there is some data after a combat left)

### CODE REVIEW

**Comment by Immemor** [comment]
Wwooow, The logger is too great.

It's magical. I can extract all the fight history to a google sheet.
Only 1 fight is needed to catch all. So great.

I will add some others commits for Maelstrom and EpLogicEarth.

**Comment by Immemor** [comment]
Here an example of log extraction in color:

https://docs.google.com/spreadsheets/d/17MY1aoLPQ9HPUc0m_gio57MVgXDdDYUjQZTC0ku4KRg/edit#gid=0

It was us first time on Elemental Pair Megalith and Mnemesis

I found 2 small bugs, I will fix them today.

PS: You can play with the google sheet, I think I will write a wiki page about how to use log.

**Comment by NielsH** [comment]
This looks absolutely amazing, really awesome! :+1: 

Will try this out in GA when we do it this week to get a feel with the working of it.

For your commit message, I am aware that some styling guidelines recommend a 79 character limit (https://www.python.org/dev/peps/pep-0008/#id14) . For me this is very frustrating and too short, but I'm okay if you want to agree on a longer length. Python suggests 100 characters, I would be a fan of 120 or so, but if you don't want to 100 would be okay too.

**Comment by Immemor** [comment]
Woww, you known the PEP8. I'm surprised.

Hum, why not, Let's say 100 so. I will change commit to this new directive

**Comment by Immemor** [comment]
I wrote a wiki page ( https://github.com/NielsH/RaidCore/wiki/How-to-use-Logs ) to help. Is it enough ?

**Comment by NielsH** [comment]
It looks sufficient, but I haven't had the chance yet to test it in the
raid itself. We cleared DS for this week, so I'll test it in GA when we do
it this reset. If any questions pop up I'm gonna let you know! :-)

EDIT: And yeah, I know PEP8, I'm just horrible at following it :D But for small personal python projects vim has a PEP8 checker I use to make sure it's compliant ;)

**Comment by Immemor** [comment]
I was thinking, you use Visual Studio. I see a file with a tag.

Well, I use VIM too.
Under linux, you have pep8 package to check compliance.
If you want use something else, tell me. I will configure my vim like u so.

**Comment by NielsH** [comment]
For Windows, with RaidCore, I use Sublime as editor, mostly default, with a 4-space tabsize.

For my Python projects I use vim on Linux indeed, though never used that with Raidcore since it's a hassle to do it via SSH when the code itself has to be run via Windows :)

I'll check tomorrow for some Sublime code compliance plugins, will hopefully make it easier to uphold the 100 char limit and styling and such ^^

**Comment by Immemor** [comment]
after I we speak about coding style, I have a preference for space than tab. Like pep8.
It's easier to align arguments with brackets. ^^

**Comment by NielsH** [comment]
I'm fine with spaces as tabs, though I would really like 4 spaces - not 2 :p 

I tested it out this week in GA and seemed to work well!

**Comment by Immemor** [comment]
Oki, The CombatInterface.lua come from DruseraBossMods. I was more focus on the adaption to RaidCore than coding style.

And I chosen 2 spaces because lua language is very expansive. But If you want 4 spaces, well why not. I will add it in my todo list for next branch proposal.

**Comment by Immemor** [comment]
I found some very small bug, or cpu improvements to do. I updated this branch so.

**Comment by Immemor** [comment]
For the April delivery, obviously it's a little late.

I would like to continue to rework some part like:
- The zone detection feature, and so remove the Zone string.
- Improve the start combat detection also.

Can I push this branch in master ? ( another one will come for french translation )

**Comment by NielsH** [comment]
Fine with me - I didn't notice any issues with it.

What I'll probably do (hopefully today) is add a change to detect EnableEvents after a reloadui/upon login, so it for examples also activates ohmna properly after a reloadui. With that, and the change/fix for the pillars (which hopefully won't be a pain to figure out what causes it) we can then add it as a new release to Curse.

**Comment by Immemor** [comment]
hum, I was thinking to activate an encounter with EnteringCombat Events. Not with UnitCreated.

UnitCreated can be used only during the combat, not before or after. It's my current point of view.

**Comment by NielsH** [comment]
Ah well - sure. Then I will leave that to you. We should probably decide upon some action points and divide between ourselfs who does what at some point :)

**Pull request merged**
