### PR TITLE
factorize the distance computation between 2 units.

### PR DESCRIPTION
**Pull request by Immemor**
Code duplication reduction. No functional change.

### CODE REVIEW

**Comment by NielsH** [comment]
Alright, so what's the best way to merge this and https://github.com/NielsH/RaidCore/pull/39 together? Since they both edit the same files, will there be issues if I merge the pull request from one of them and then want to do the next one and it can no longer automatically merge? - Or will Git pick this up without issues?

Just to be sure :-)

**Comment by Immemor** [comment]
I can do it for you. Is 'dev' branch is updated with you last version  ?

**Comment by NielsH** [comment]
Yeah, it'd be awesome if we can get these open pull requests all into the master. I saw you also changed the toc.xml file, I did this as well in my pull request: https://github.com/NielsH/RaidCore/pull/39/files#diff-7aa658dba22bd974a204d1dda375d5b0 where I renamed some bosses as well to align better with what we have in the settings UI. 

So maybe need to be careful there the right filenames are used.

**Comment by Immemor** [comment]
Easy ^^, I did some rebase much more complicated than that in my professional life ^^

**Comment by Immemor** [comment]
Done:

Your new branch name is: https://github.com/NielsH/RaidCore/tree/dev_rebased

**Comment by Immemor** [comment]
I will try to proposal you an alternative. your branch is more at the developing state than delivery state.

**Comment by Immemor** [comment]
Ok, I rework a little bit you branch to be less "Work In Progress".

https://github.com/NielsH/RaidCore/tree/dev2
- I think you don't need to add the prefix "DS_" or "GA_".  Because Modules have their name unique, and I will add more informations with ZoneMap.
- You haven't explained changes about PhageCouncil.

**Comment by Immemor** [comment]
Also.

about elemental pair rename. By example, Hydroflux is the common boss. I was useful to have the static boss as the first in the filename, to group them by static boss.

I thinking more to EpWaterAir instead of EpAirWater.

Did you have something bigger in mind ?

**Comment by NielsH** [comment]
Hey,

The prefix is for the settings: https://github.com/NielsH/RaidCore/blob/dev2/Modules/BossPrototype.lua#L114 - since settings are prefixed with DS_ - I added it there to the bossname, so we can use the self:GetName() function

Phagecouncil: The ability, Stitching Strain is something terax does, it heals the bosses in the room. Normally you take like 2 people (tank+healer) to Terax and they interrupt the boss. This simply adds a warning for when they need to interrupt, and only if within a small range, so it doesn't give the warning for people that are fighting another boss.

For elemental pairs - sure, I don't mind changing it. I thought the "static" boss was the way it is defined now - but then again elemental pairs and the combinations are kinda confusing ^^

**Comment by Immemor** [comment]
Hum,
- I understood the tip with GetName, but change all current module names is unnecessary. That bring nothing for user, memory or cpu.
- I speaking more about the second change with Start/Stop
- So the name AirWater is a mistake ?

**Comment by NielsH** [comment]
For the first: How do you want to separate GA/DS then? Settings have a prefix, self:GetName() doesn't return that prefix unless it's in the boss name.

Second: StartScan/StopScan, that defines whether it's scanning for casts/abilities units.. I noticed that it wouldn't detect the cast starting event, so I changed it to StartScan during the duration of the encounter. Terax does cast it all throughout the encounter anyways.

For elemental pairs: if the "correct" way is the other way around and it's easier to organize that way then sure. I don't think it really matters functionality wise :)

**Comment by Immemor** [comment]
- Currently, there is no need to split GA and DS. The combinaison : ModuleName + '_' + myoption should provide a unique key for all encounter.
- Ok, you can add it in the commit message so, to diffuse the knowledge.
- Ok, as u wish in fact. It's just to follow your mind.

Did you see the dev2 branch ? I tried to help you.

**Comment by NielsH** [comment]
Alright.. I've changed the settings. See: https://github.com/NielsH/RaidCore/commit/0e7ad0d350707622b1df9bab3def197c1b160b54

Also added in commit msg: https://github.com/NielsH/RaidCore/commit/19db2f8800e5353b3633ac825f24f7cc2c5e30ac

**Pull request closed without merging**
