### PR TITLE
Harmonize addtimerbar #150

### PR DESCRIPTION
**Pull request by olbat**

### CODE REVIEW

**Comment by Immemor** [comment]
Commit pushed in master, I did the conflict resolution myself. Because I don't want to learn it with web tool like github. I prefer shell, like on linux system.

**Comment by olbat** [comment]
Perfect ! BTW, I prefer the CLI too :)

**Comment by olbat** [comment]
I was just thinking, if my commit is based on a scripted modification like this one, it'll proly take me less time to re-apply the script on the top of the master branch than for you to fix the conflicts.
Don't hesitate to ask me to re-apply the script if it happens again :)

**Comment by Immemor** [comment]
^^ don't worry, with git, it's very easy to solve.

**Pull request closed without merging**
