### PR TITLE
Encounters/DS: Update LogicLife, refs #35

### PR DESCRIPTION
**Pull request by Immemor**
- Replace buff identification string by spellId, refs #35
- Update french language
- delete useless function which is 'OnReset'.

### CODE REVIEW

**Comment by Immemor** [comment]
Note: I will retest this commit on Sunday night.

**Comment by Immemor** [comment]
Tested.

**Comment by Immemor** [comment]
Are u ok to merge that ?

**Comment by NielsH** [comment]
Sure

**Pull request merged**
