### PR TITLE
Encounters/GA/Kuralak: Bugfix, players that have the Chromosome Corru…

### PR DESCRIPTION
**Pull request by olbat**
…ption debuff are no longer marked, refs #145

### CODE REVIEW

**Comment by Immemor** [comment]
Done by me, but pushed later with others

**Comment by olbat** [comment]
Erm, I was just thinking, will it be possible to make a release for the version 3.11 ? (not only an alpha pre-release)

**Comment by Immemor** [comment]
Hum, I have a small bug on Air/Logic.

The line between player with thunder and tree is not drawed.

But it's a small bug. I could set the 3.12-alpha as a release.

**Comment by Immemor** [comment]
Finally, that will wait the #126.

My first result are unbelievable.
RaidCore Graph

**Comment by olbat** [comment]
Omg, what a great improvement ! Nice :)

**Pull request closed without merging**
