### PR TITLE
Encounters/Y83: Add Prime Evolutionary Operant encounter, refs #91

### PR DESCRIPTION
**Pull request by Immemor**
First feedback in easy mode.

### CODE REVIEW

**Comment by Immemor** [comment]
Are you agree to push for 2.0 this first implementation of Y83, or do u want delay it for 3.0 ?

**Comment by NielsH** [comment]
Sure, I would just change the above thing that I mentioned, but I do want it in for 2.0 to get some feedback on the initial stuff for the encounter.

I expect to be there next reset as well so can log a bit and add some things as well :+1:

**Comment by Immemor** [comment]
Changes done. 
When the encounter will be more defined, at this moment we can close the #91. It's why I put it in refs.

But I you don't like I can close the issue to avoid the overlap between milestone.

**Comment by NielsH** [comment]
Great. I'm fine with keeping it open for now :)

**Pull request merged**
