### PR TITLE
add pkgmeta file for automatic delivery

### PR DESCRIPTION
**Pull request by Immemor**
See: http://wildstar.curseforge.com/docs/packaging

### CODE REVIEW

**Comment by NielsH** [comment]
Alright, I have configured this to package tagged commits. We'll have to test it with some alpha release, and I want to make sure that we give users a proper changelog that they can read/understand so they know what's new. By default it just copies in the git commits which aren't really clear.

**Comment by Immemor** [comment]
Ok. Hum I would like to test this pull request feature, as it's my first time on github (not in git).
The result of this request is quite dirty.

You didn't have an option to Pull and rebase like:

``` zsh
git pull --rebase
```

How do you process  ? with a graphical interface or in command line ?

**Comment by NielsH** [comment]
Hm? I just click on Merge Pull Request in the Github web UI ( https://github.com/NielsH/RaidCore/compare ). That's how I create my own pull requests as well.

For git itself I just use the default Github windows software - https://windows.github.com/

**Comment by Immemor** [comment]
Ok, I will see If I can configure the project with .git/config file. And so to rebase by default.

**Pull request merged**
