### PR TITLE
Encounters/GA: Improve French translations for Kuralak

### PR DESCRIPTION
**Pull request by olbat**
I also update the [log's gist](https://gist.github.com/olbat/5c31432b381fa63df915).

(+ it seems that one translation was wrong)

### CODE REVIEW

**Comment by Immemor** [comment]
I don't like this encounter description, based on NPCSays, it's horrible to maintain.

I will have look your log, and try to rewrite it.

**Comment by Immemor** [comment]
Strange, your raw files have many end of lines, which means it's not a JSON format but something between JSON and CSV.

Well, I should be able to use it.

**Comment by olbat** [comment]
I just wrapped the files using a script for them to be easier to read but it's still valid JSON :)

**Comment by olbat** [comment]
And I agree, code based on NPCSay is hard to maintain and to translate, I'll take a look at the logs too :)

**Comment by olbat** [comment]
You're right for the comma, really sorry I did not raid since my fix so I did not have any occasion to test it ...

For the "...", I removed them because they were removed from the English dialog too (there is "..." at the en of the English NPCSay).

**Comment by Immemor** [comment]
I didn't get any log in english, but for me. It's the english which is wrong.

But that doesn't matter now. I rebuilt the kuralak fight. I will push in separate branch for validation by you or any another guy, after my datascape raid.

Just after I push an official version.

**Comment by olbat** [comment]
Okay, I don't think this is the only boss English messages are striped like this ...
I'm pretty sure I saw this in other encounter files, I always thought that it was made on purpose (since `String.find` is used to check the match -> it's working).

**Comment by olbat** [comment]
I'll send some English dumps next week.

**Comment by Immemor** [comment]
or, you can try my wip/ga branch. ^^

**Pull request merged**
